Feat: Metadata HTTP Cache + LehavaMock 5s response delay on Metadata requests
AlphaWolfsTeam/tommy pull request #238
Opened 2020-12-23 20:21 UTC by AdarPascal

2020-12-24 14:44 UTC, ShragaUser requested changes
overall really good job. 
its on point. 

notice points about graceful error handling on redis fail.

2020-12-24 14:44 UTC, ShragaUser commented on tommy-server/src/metadata-cache/metadataCache.ts
> +            next();
return next(); same line.

2020-12-24 14:44 UTC, ShragaUser commented on tommy-server/src/metadata-cache/metadataCache.ts
> +            res.send(redisCachedResponse);
return next(); same line.

2020-12-24 14:44 UTC, ShragaUser commented on tommy-server/src/metadata-cache/metadataCache.ts
> +                headers: headers,
use implicit property naming 
{ headers, method: "GET"}

2020-12-24 14:44 UTC, ShragaUser commented on tommy-server/src/metadata-cache/metadataCache.ts
> +        const redisCachedResponse = JSON.parse(await MetadataCache.getRedis(req.originalUrl));
if an error happens -> JSON.parse would fail. 
is this handled in outside scope? 

redis fail should be graceful.

2020-12-24 14:44 UTC, ShragaUser commented on tommy-server/src/config.ts
> +    fullHost: process.env.LEHAVA_FULL_HOST || "lehava-api-mock:8050",
why not build using existing config properties?

2020-12-24 14:44 UTC, ShragaUser commented on tommy-server/src/config.ts
> +    requestTypesToCache: ['nr', 'z_networks_to_service', 'pcat', 'chgcat', 'z_pcat_to_network', 'z_chgcat_to_network'],
make this configurable by environment variables. 
consider using split by ',' from env

2020-12-25 18:56 UTC, AdarPascal commented
@ShragaUser
What do you think about _7d9fbb7_ commit ?
Added Redis error and disconnection handle, plus all of your corrections.

2020-12-25 20:37 UTC, ShragaUser approved these changes
LGTM

2020-12-26 15:35 UTC, merged